# Site settings
title: Cristian D'Ortona
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cristian D'Ortona
user-description : descr
user_title: Electronics Engineer
email: cristian.dortona@studio.unibo.it

# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
