# Site settings
title: Cristian D'Ortona
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "cdortona.com" 

# User settings
username: Cristian D'Ortona
user-description : descr
user_title: Electronics Engineer
email: cristian.dortona@studio.unibo.it

# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
